### ISSUE TITLE
Design System, Components, React Modal grey background

### ISSUE THREAD

**Issue by bgirardot** [hotosm/oam-docs#41]
I think the back ground needs to be grayed out with the modal dialog content white background.

Keeping the background white, but only blurred, does not define the area of the modal dialog content enough or indicate there is a new, important focus and message.

It just looks like the page morphs, instead of clearly indicating this is a modal context switch, the main page is now "disabled" and the modal dialog content is now the focus and is "boxed" or "framed" so I know its exact extent.

**Comment by smit1678** [comment]
Added this over in the `oam-design-system` repo to track in the core style: https://github.com/hotosm/oam-design-system/issues/24.
